ALTER TABLE nibrs_arrestee DISABLE TRIGGER ALL;
ALTER TABLE nibrs_arrestee_weapon DISABLE TRIGGER ALL;
ALTER TABLE nibrs_bias_motivation DISABLE TRIGGER ALL;
ALTER TABLE nibrs_month DISABLE TRIGGER ALL;
ALTER TABLE nibrs_incident DISABLE TRIGGER ALL;
ALTER TABLE nibrs_offender DISABLE TRIGGER ALL;
ALTER TABLE nibrs_offense DISABLE TRIGGER ALL;
ALTER TABLE nibrs_property DISABLE TRIGGER ALL;
ALTER TABLE nibrs_property_desc DISABLE TRIGGER ALL;
ALTER TABLE nibrs_suspect_using DISABLE TRIGGER ALL;
ALTER TABLE nibrs_suspected_drug DISABLE TRIGGER ALL;
ALTER TABLE nibrs_victim DISABLE TRIGGER ALL;
ALTER TABLE nibrs_victim_circumstances DISABLE TRIGGER ALL;
ALTER TABLE nibrs_victim_injury DISABLE TRIGGER ALL;
ALTER TABLE nibrs_victim_offender_rel DISABLE TRIGGER ALL;
ALTER TABLE nibrs_victim_offense DISABLE TRIGGER ALL;
ALTER TABLE nibrs_weapon DISABLE TRIGGER ALL;
ALTER TABLE nibrs_criminal_act DISABLE TRIGGER ALL;

\COPY agencies_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/agencies.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_ACTIVITY_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_ACTIVITY_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_AGE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_AGE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_ARREST_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_ARREST_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_ASSIGNMENT_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_ASSIGNMENT_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_BIAS_LIST_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_BIAS_LIST.csv' DELIMITER ',' HEADER CSV encoding 'windows-1251';
\COPY NIBRS_LOCATION_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_LOCATION_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_OFFENSE_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_OFFENSE_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_PROP_LOSS_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_PROP_LOSS_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_PROP_DESC_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_PROP_DESC_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_CIRCUMSTANCES_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_CIRCUMSTANCES.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_CLEARED_EXCEPT_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_CLEARED_EXCEPT.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_CRIMINAL_ACT_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_CRIMINAL_ACT.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_CRIMINAL_ACT_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_CRIMINAL_ACT_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_DRUG_MEASURE_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_DRUG_MEASURE_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_ETHNICITY_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_ETHNICITY.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_INJURY_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_INJURY.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_RELATIONSHIP_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_RELATIONSHIP.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_SUSPECTED_DRUG_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_SUSPECTED_DRUG_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_USING_LIST_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_USING_LIST.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_WEAPON_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_WEAPON_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY REF_RACE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/REF_RACE.csv' DELIMITER ',' HEADER CSV;
\COPY REF_STATE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/REF_STATE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_ARRESTEE_WEAPON_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_ARRESTEE_WEAPON.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_BIAS_MOTIVATION_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_BIAS_MOTIVATION.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_VICTIM_TYPE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_VICTIM_TYPE.csv' DELIMITER ',' HEADER CSV;
\COPY NIBRS_JUSTIFIABLE_FORCE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_JUSTIFIABLE_FORCE.csv' DELIMITER ',' HEADER CSV;

\COPY NIBRS_ARRESTEE_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_ARRESTEE.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_month_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_month.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_incident_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_incident.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_offender_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_OFFENDER.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_offense_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_OFFENSE.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_property_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_PROPERTY.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_property_desc_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_PROPERTY_DESC.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_suspect_using_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_SUSPECT_USING.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_suspected_drug_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_SUSPECTED_DRUG.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_victim_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_VICTIM.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_victim_circumstances_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_VICTIM_CIRCUMSTANCES.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_victim_injury_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_VICTIM_INJURY.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_victim_offender_rel_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_VICTIM_OFFENDER_REL.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_victim_offense_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_VICTIM_OFFENSE.csv' DELIMITER ',' HEADER CSV;
\COPY nibrs_weapon_2022 FROM '/Users/prosas/Documents/Crime Project/NY-2022-Files/NIBRS_WEAPON.csv' DELIMITER ',' HEADER CSV;


ALTER TABLE nibrs_arrestee ENABLE TRIGGER ALL;
ALTER TABLE nibrs_arrestee_weapon ENABLE TRIGGER ALL;
ALTER TABLE nibrs_bias_motivation ENABLE TRIGGER ALL;
ALTER TABLE nibrs_month ENABLE TRIGGER ALL;
ALTER TABLE nibrs_incident ENABLE TRIGGER ALL;
ALTER TABLE nibrs_offender ENABLE TRIGGER ALL;
ALTER TABLE nibrs_offense ENABLE TRIGGER ALL;
ALTER TABLE nibrs_property ENABLE TRIGGER ALL;
ALTER TABLE nibrs_property_desc ENABLE TRIGGER ALL;
ALTER TABLE nibrs_suspect_using ENABLE TRIGGER ALL;
ALTER TABLE nibrs_suspected_drug ENABLE TRIGGER ALL;
ALTER TABLE nibrs_victim ENABLE TRIGGER ALL;
ALTER TABLE nibrs_victim_circumstances ENABLE TRIGGER ALL;
ALTER TABLE nibrs_victim_injury ENABLE TRIGGER ALL;
ALTER TABLE nibrs_victim_offender_rel ENABLE TRIGGER ALL;
ALTER TABLE nibrs_victim_offense ENABLE TRIGGER ALL;
ALTER TABLE nibrs_weapon ENABLE TRIGGER ALL;
ALTER TABLE nibrs_criminal_act ENABLE TRIGGER ALL;